### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by radaniba** [marklogic-community/envision#142]
Hello

I am using Envision 2.0.1 with DH 10 and DHF 5.2.6

I encountered a problem in all the borwser that I tried, when I try to do the mapping, the selector of attributes is not popping up the attributes to select from 

<img width="1237" alt="Screen Shot 2020-12-16 at 9 40 44 pm" src="https://user-images.githubusercontent.com/1666443/102356254-f1b37f80-3fe7-11eb-8949-8d4bc1d15c09.png">

There are several JavaScript errors on the console as well 

```
21:39:18.393 [http-nio-9003-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.FailedRequestException: Local message: write failed: Internal Server Error. Server Message: JS-JAVASCRIPT: let namespacePrefix = entityDefinition.namespacePrefix; -- Error running JavaScript request: TypeError: Cannot read property 'namespacePrefix' of undefined . See the MarkLogic server error log for further detail.] with root cause
com.marklogic.client.FailedRequestException: Local message: write failed: Internal Server Error. Server Message: JS-JAVASCRIPT: let namespacePrefix = entityDefinition.namespacePrefix; -- Error running JavaScript request: TypeError: Cannot read property 'namespacePrefix' of undefined

```

Any idea?

Thanks

**Comment by paxtonhare** [comment]
@radaniba we have a fix coming for this in 2.0.2. it's already in the develop branch.

**Comment by radaniba** [comment]
Thank you @paxtonhare any idea on the release date ?

**Comment by wpaven** [comment]
fixed in 2.0.2

**Comment by radaniba** [comment]
Hi @paxtonhare and @wpaven 
This bug still exists on 2.0.2

Actually only chrome works well, I tested Firefox and Safari and the bug is still there

Cheers,
Rad

**Comment by wpaven** [comment]
Thanks @radaniba  You may have a caching issue.  We test with both Chrome and Firefox.  I'm using Firefox predominately myself.  We don't do any testing with Safari.
